dist: trusty

addons:
  postgresql: "9.5"
  apt:
    packages:
      - curl
      - wget
      - ca-certificates
      - build-essential
      - postgresql-9.5
      - postgresql-contrib-9.5
      - postgresql-server-dev-9.5

language: c

cache: cargo

services:
  - postgresql

before_install:
  - curl -o rustup_install.sh https://sh.rustup.rs -sSf && sh rustup_install.sh -y
  - export PATH=$HOME/.cargo/bin:$PATH

install:
  - make
  - sudo env PATH=$PATH make install

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./setup_regress presto && travis_wait 40 make installcheck; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./setup_regress hive && travis_wait 40 make installcheck; fi'
